/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Bicicleta;
import model.Manutencao;
import dao.ManutencaoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import dao.BicicletaDAO;



/**
 *
 * @author cleri
 */
public class TelaManutencao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaManutencao.class.getName());

    /**
     * Creates new form TelaManutencao
     */
    
    private void preencherComboBicicletas() {
    try {
        bicicletas.clear();
        List<Bicicleta> lista = new BicicletaDAO().read();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Bicicleta b : lista) {
            bicicletas.add(b);                   // guarda o objeto para uso futuro
            model.addElement(b.getCodigo());     // mostra o código (ou outro campo)
        }
        cbBicicletas.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar bicicletas: " + e.getMessage());
        e.printStackTrace();
    }
}
    public TelaManutencao() {
        initComponents();
        preencherComboBicicletas();
    }
    
    private List<Bicicleta> bicicletas = new ArrayList<>();
    
    public void ListarManutencao(){
        List<Manutencao> lista = new ManutencaoDAO().read();
    DefaultTableModel modelo = (DefaultTableModel) tabelaManutencao.getModel();

    // Define cabeçalhos (opcional — se você já configurou no NetBeans ignore essa linha)
    modelo.setColumnIdentifiers(new Object[] {"ID", "Bicicleta", "Data", "Descrição"});

    modelo.setRowCount(0);
    BicicletaDAO bdao = new BicicletaDAO();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    for (Manutencao m : lista) {
        String codigoBicicleta = "";
        try {
            // tenta buscar a bicicleta pelo id para obter o código/nome
            model.Bicicleta b = bdao.findById(m.getBicicletaId()); // ajuste o pacote/nome se necessário
            if (b != null) {
                codigoBicicleta = b.getCodigo(); // ou b.getNome()
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        String dataStr = m.getData() != null ? sdf.format(m.getData()) : "";
        modelo.addRow(new Object[]{ m.getId(), codigoBicicleta, dataStr, m.getDescricao() });
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbBicicletas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        txtData = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaManutencao = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbBicicletas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tabelaManutencao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Bicicleta", "Data", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaManutencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaManutencaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaManutencao);

        jLabel1.setText("Data");

        jLabel2.setText("Bicicletas");

        jLabel3.setText("Descricao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(cbBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRegistar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnListar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(jLabel1)
                            .addGap(84, 84, 84)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistar)
                            .addComponent(btnListar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
 try {
        Manutencao m = new Manutencao();
        m.setDescricao(txtDescricao.getText());

        // Pegar bicicleta selecionada pelo índice (você já mantém a lista 'bicicletas')
        int idx = cbBicicletas.getSelectedIndex();
        if (idx < 0 || idx >= bicicletas.size()) {
            JOptionPane.showMessageDialog(this, "Selecione uma bicicleta antes de registrar.");
            return;
        }
        Bicicleta bicicletaSelecionada = bicicletas.get(idx);
        m.setBicicletaId(bicicletaSelecionada.getId());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date data = sdf.parse(txtData.getText());
        m.setData(data);
        ManutencaoDAO dao = new ManutencaoDAO();
        dao.create(m);
        ListarManutencao();
        JOptionPane.showMessageDialog(null, "Manutenção registrada com sucesso!");
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(null, "Data inválida! Use o formato dd/MM/yyyy.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao registrar manutenção: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        ListarManutencao();
    }//GEN-LAST:event_btnListarActionPerformed

    private void tabelaManutencaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaManutencaoMouseClicked
        // TODO add your handling code here:
int row = tabelaManutencao.getSelectedRow();
    if (row != -1) {
        Object bicObj = tabelaManutencao.getValueAt(row, 1);
        cbBicicletas.setSelectedItem(bicObj != null ? bicObj.toString() : "");
        Object dataObj = tabelaManutencao.getValueAt(row, 2);
        txtData.setText(dataObj != null ? dataObj.toString() : "");
        Object descObj = tabelaManutencao.getValueAt(row, 3);
        txtDescricao.setText(descObj != null ? descObj.toString() : "");
    }
    }//GEN-LAST:event_tabelaManutencaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaManutencao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JComboBox<String> cbBicicletas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaManutencao;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
