/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Locacao;
import dao.LocacaoDAO;
import model.Bicicleta;
import dao.BicicletaDAO;
import model.Cliente;
import dao.ClienteDAO;
import model.Manutencao;
import dao.ManutencaoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;



/**
 *
 * @author cleri
 */
public class TelaRelatorios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorios.class.getName());

    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios() {
        initComponents();
         DefaultTableModel modelo = (DefaultTableModel) tabelaRelatorios.getModel();
        modelo.setColumnIdentifiers(new Object[] {"ID","Cliente","Bicicleta","Data Início","Data Fim","Status"});
        modelo.setRowCount(0);
    }
    
    public void listarLocacoes() {
 List<Locacao> lista = new LocacaoDAO().read();
 DefaultTableModel modelo = (DefaultTableModel)
 tabelaRelatorios.getModel();
 modelo.setRowCount(0);
for (Locacao l : lista) {
 modelo.addRow(new Object[]{l.getId(), l.getClienteId(),
 l.getBicicletaId(), l.getDataInicio(), l.getDataFim(), l.getStatus()});
 }
 }
    
    public void listarManutencoes() {
    List<Manutencao> lista = new ManutencaoDAO().read();
    DefaultTableModel modelo = (DefaultTableModel) tabelaRelatorios.getModel();
    modelo.setRowCount(0);
    for (Manutencao m : lista) {
        modelo.addRow(new Object[]{ m.getId(), m.getBicicletaId(), m.getData(), m.getDescricao() });
    }
}

public void listarBicicletas() {
    List<Bicicleta> lista = new BicicletaDAO().read();
    DefaultTableModel modelo = (DefaultTableModel) tabelaRelatorios.getModel();
    modelo.setRowCount(0);
    for (Bicicleta b : lista) {
        modelo.addRow(new Object[]{ b.getId(), b.getCodigo(), b.getStatus() });
    }
}

public void listarClientes() {
    List<Cliente> lista = new ClienteDAO().read();
    DefaultTableModel modelo = (DefaultTableModel) tabelaRelatorios.getModel();
    modelo.setRowCount(0);
    for (Cliente c : lista) {
        modelo.addRow(new Object[]{ c.getId(), c.getNome(), c.getCpf(), c.getTelefone(), c.getEmail() });
    }
}
    
    
    
 public void gerarRelatorio(String tipo) {
 switch(tipo) {
 case "Clientes":
 listarClientes();
 break;
 case "Bicicletas":
 listarBicicletas();
 break;
 case "Locações":
 listarLocacoes();
 break;
 case "Manutenções":
 listarManutencoes();
 break;
 }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTipoRelatorio = new javax.swing.JComboBox<>();
        btnGerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelatorios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes", "Bicicletas", "Locações", "Manutenções" }));

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        tabelaRelatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaRelatorios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerar)
                    .addComponent(cbTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(cbTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(btnGerar)
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
String tipo = (String) cbTipoRelatorio.getSelectedItem();
    if (tipo != null) {
        gerarRelatorio(tipo);
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um tipo de relatório.");
    }
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRelatorios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JComboBox<String> cbTipoRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaRelatorios;
    // End of variables declaration//GEN-END:variables
}
